apiVersion: v1
kind: Secret
metadata:
  name: auto-insurance-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://USER:PASSWORD@cluster0.mongodb.net/auto_insurance_db?retryWrites=true&w=majority"
